import { motion, AnimatePresence } from 'framer-motion'
import { FileText, User, Download, X, Eye } from 'lucide-react'
import { useState } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

interface ReportsTabProps {
  reports: { agentId: string; filename: string; summary: string }[]
  projectPath: string
}

export default function ReportsTab({ reports, projectPath }: ReportsTabProps) {
  const [selectedReport, setSelectedReport] = useState<any>(null)
  const [reportContent, setReportContent] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const handlePreview = async (report: any) => {
    setIsLoading(true)
    setSelectedReport(report)
    try {
      // In our current implementation, saveReport uses writeFile (text).
      // We need a readText method or just use readJson if it was saved as JSON.
      // Since it's .md, it's text. Let's add readText to window.api.
      const content = await window.api.readText(projectPath, `Reports/${report.filename}`)
      setReportContent(content)
    } catch (err) {
      console.error('Failed to read report:', err)
      setReportContent('Failed to load report content.')
    } finally {
      setIsLoading(false)
    }
  }

  if (reports.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center space-y-4 opacity-40">
        <FileText className="w-12 h-12" />
        <p className="text-sm font-medium">No reports generated yet.</p>
      </div>
    )
  }

  return (
    <div className="max-w-5xl mx-auto w-full space-y-8 h-full">
      <div className="space-y-2">
        <h1 className="text-4xl font-semibold tracking-tight">Project Strategy</h1>
        <p className="text-muted-foreground font-medium">Comprehensive analysis generated by your strategy team.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-20">
        {reports.map((report, index) => (
          <motion.div
            key={report.agentId}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="group bg-background border border-border rounded-[2rem] p-8 hover:shadow-2xl hover:shadow-primary/5 transition-all flex flex-col justify-between"
          >
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                 <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                    <User className="w-3.5 h-3.5" />
                    <span>{report.agentId.replace('_', ' ')}</span>
                 </div>
              </div>

              <h3 className="text-2xl font-semibold capitalize tracking-tight">{report.agentId.replace('_', ' ')} Report</h3>
              <p className="text-sm text-muted-foreground line-clamp-4 leading-relaxed font-medium">
                {report.summary}
              </p>
            </div>

            <div className="flex gap-3 mt-8">
               <button
                onClick={() => handlePreview(report)}
                className="flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl bg-primary text-primary-foreground hover:opacity-90 transition-all text-sm font-bold shadow-lg shadow-primary/10"
              >
                <Eye className="w-4 h-4" />
                Preview
              </button>
              <button
                onClick={async () => {
                   const fullPath = await window.api.join(projectPath, 'Reports', report.filename)
                   window.api.openPath(fullPath)
                }}
                className="p-3 rounded-2xl bg-secondary hover:bg-border transition-all"
                title="Open in native editor"
              >
                <Download className="w-5 h-5 opacity-50" />
              </button>
            </div>
          </motion.div>
        ))}
      </div>

      <AnimatePresence>
        {selectedReport && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setSelectedReport(null)}
              className="fixed inset-0 bg-background/80 backdrop-blur-md z-[100]"
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="fixed inset-4 md:inset-10 lg:inset-20 bg-background border border-border shadow-2xl rounded-[2.5rem] z-[110] flex flex-col overflow-hidden"
            >
              <div className="p-8 border-b border-border flex items-center justify-between bg-secondary/20">
                <div className="flex items-center gap-4">
                  <div className="p-3 bg-primary rounded-2xl">
                    <FileText className="w-6 h-6 text-primary-foreground" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold tracking-tight capitalize">{selectedReport.agentId.replace('_', ' ')} Strategy</h2>
                    <p className="text-sm text-muted-foreground font-medium">Detailed Specialist Report</p>
                  </div>
                </div>
                <button
                  onClick={() => setSelectedReport(null)}
                  className="p-3 hover:bg-secondary rounded-full transition-colors"
                >
                  <X className="w-6 h-6" />
                </button>
              </div>

              <div className="flex-1 overflow-y-auto p-8 md:p-12 lg:p-16">
                {isLoading ? (
                  <div className="h-full flex flex-col items-center justify-center space-y-4 opacity-40">
                     <div className="w-12 h-12 border-4 border-primary border-t-transparent rounded-full animate-spin" />
                     <p className="font-bold uppercase tracking-widest text-xs">Loading report content...</p>
                  </div>
                ) : (
                  <div className="prose prose-zinc max-w-none prose-headings:tracking-tight prose-headings:font-bold prose-p:leading-relaxed prose-p:text-muted-foreground prose-strong:text-foreground">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>
                      {reportContent}
                    </ReactMarkdown>
                  </div>
                )}
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  )
}
