import { motion } from 'framer-motion'
import { FileText, ExternalLink, Calendar, User } from 'lucide-react'

interface ReportsTabProps {
  reports: { agentId: string; filename: string; summary: string }[]
  onOpenReport: (filename: string) => void
}

export default function ReportsTab({ reports, onOpenReport }: ReportsTabProps) {
  if (reports.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center space-y-4 opacity-40">
        <FileText className="w-12 h-12" />
        <p className="text-sm font-medium">No reports generated yet.</p>
      </div>
    )
  }

  return (
    <div className="max-w-5xl mx-auto w-full space-y-8">
      <div className="space-y-2">
        <h1 className="text-4xl font-semibold tracking-tight">Project Strategy</h1>
        <p className="text-muted-foreground">Comprehensive analysis generated by your strategy team.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-20">
        {reports.map((report, index) => (
          <motion.div
            key={report.agentId}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="group bg-white border border-black/5 rounded-2xl p-6 hover:shadow-xl hover:shadow-black/5 transition-all flex flex-col justify-between"
          >
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                 <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-black/40">
                    <User className="w-3 h-3" />
                    <span>{report.agentId.replace('_', ' ')}</span>
                 </div>
                 <div className="flex items-center gap-2 text-[10px] text-muted-foreground">
                    <Calendar className="w-3 h-3" />
                    <span>Just now</span>
                 </div>
              </div>

              <h3 className="text-xl font-semibold capitalize">{report.agentId.replace('_', ' ')} Report</h3>
              <p className="text-sm text-muted-foreground line-clamp-3 leading-relaxed">
                {report.summary}
              </p>
            </div>

            <button
              onClick={() => onOpenReport(report.filename)}
              className="mt-6 flex items-center justify-center gap-2 w-full py-2.5 rounded-xl border border-black/5 hover:bg-black hover:text-white transition-all text-sm font-medium"
            >
              Open Report
              <ExternalLink className="w-4 h-4" />
            </button>
          </motion.div>
        ))}
      </div>
    </div>
  )
}
