import { motion, AnimatePresence } from 'framer-motion'
import { FileText, User, Download } from 'lucide-react'
import { useState } from 'react'

interface ReportsTabProps {
  reports: { agentId: string; filename: string; summary: string }[]
  projectPath: string
}

export default function ReportsTab({ reports, projectPath }: ReportsTabProps) {
  if (reports.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center space-y-4 opacity-40">
        <FileText className="w-12 h-12" />
        <p className="text-sm font-medium">No reports generated yet.</p>
      </div>
    )
  }

  return (
    <div className="max-w-5xl mx-auto w-full space-y-8">
      <div className="space-y-2">
        <h1 className="text-4xl font-semibold tracking-tight">Project Strategy</h1>
        <p className="text-muted-foreground font-medium">Comprehensive analysis generated by your strategy team.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pb-20">
        {reports.map((report, index) => (
          <motion.div
            key={report.agentId}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="group bg-background border border-border rounded-[2rem] p-8 hover:shadow-2xl hover:shadow-primary/5 transition-all flex flex-col justify-between"
          >
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                 <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
                    <User className="w-3.5 h-3.5" />
                    <span>{report.agentId.replace('_', ' ')}</span>
                 </div>
              </div>

              <h3 className="text-2xl font-semibold capitalize tracking-tight">{report.agentId.replace('_', ' ')} Report</h3>
              <p className="text-sm text-muted-foreground line-clamp-4 leading-relaxed font-medium">
                {report.summary}
              </p>
            </div>

            <button
              onClick={async () => {
                 const fullPath = await window.api.join(projectPath, 'Reports', report.filename)
                 window.api.openPath(fullPath)
              }}
              className="mt-8 flex items-center justify-center gap-2 w-full py-4 rounded-2xl bg-secondary hover:bg-primary hover:text-primary-foreground transition-all text-sm font-bold"
            >
              Open Markdown Report
              <Download className="w-4 h-4 opacity-50" />
            </button>
          </motion.div>
        ))}
      </div>
    </div>
  )
}
